//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tests.TfsDeployer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SerializedDeploymentMappings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SerializedDeploymentMappings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tests.TfsDeployer.SerializedDeploymentMappings", typeof(SerializedDeploymentMappings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DeploymentMappings xmlns=&quot;http://www.readify.net/TfsDeployer/DeploymentMappings20100214&quot;&gt;
        ///  &lt;Mapping Computer=&quot;localhost&quot;
        ///           OriginalQuality=&quot;Passed&quot;
        ///           Script=&quot;Deploy.ps1&quot;
        ///           NotificationAddress=&quot;nobody@nowhere.test&quot; /&gt;
        ///&lt;/DeploymentMappings&gt;.
        /// </summary>
        internal static string AbsentNewQuality {
            get {
                return ResourceManager.GetString("AbsentNewQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DeploymentMappings xmlns=&quot;http://www.readify.net/TfsDeployer/DeploymentMappings20100214&quot;&gt;
        ///  &lt;Mapping Computer=&quot;localhost&quot;
        ///           NewQuality=&quot;Passed&quot;
        ///           Script=&quot;Deploy.ps1&quot;
        ///           NotificationAddress=&quot;nobody@nowhere.test&quot; /&gt;
        ///&lt;/DeploymentMappings&gt;.
        /// </summary>
        internal static string AbsentOriginalQuality {
            get {
                return ResourceManager.GetString("AbsentOriginalQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DeploymentMappings xmlns=&quot;http://www.readify.net/TfsDeployer/DeploymentMappings20100214&quot;&gt;
        ///  &lt;Mapping Computer=&quot;localhost&quot;
        ///           OriginalQuality=&quot;Passed&quot;
        ///           NewQuality=&quot;Other&quot;
        ///           Script=&quot;Deploy.ps1&quot;
        ///           NotificationAddress=&quot;nobody@nowhere.test&quot; /&gt;
        ///&lt;/DeploymentMappings&gt;.
        /// </summary>
        internal static string AbsentRetainBuild {
            get {
                return ResourceManager.GetString("AbsentRetainBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DeploymentMappings xmlns=&quot;http://www.readify.net/TfsDeployer/DeploymentMappings20100214&quot;&gt;
        ///
        ///  &lt;Mapping BuildDefinitionPattern=&quot;MyBuildDefA&quot;
        ///           Computer=&quot;BuildServerA&quot;
        ///           OriginalQuality=&quot;*&quot;
        ///           NewQuality=&quot;Under Investigation&quot;
        ///           Script=&quot;PrepareForInvestigation.ps1&quot; /&gt;
        ///
        ///  &lt;Mapping BuildDefinitionPattern=&quot;MyBuildDefB&quot;
        ///           Computer=&quot;AnotherBuildServer&quot;
        ///           OriginalQuality=&quot;Under Investigation&quot;
        ///           NewQuality=&quot;Ready for Deployment&quot;
        ///           Scri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompleteDeployerConfiguration {
            get {
                return ResourceManager.GetString("CompleteDeployerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DeploymentMappings xmlns=&quot;http://www.readify.net/TfsDeployer/DeploymentMappings20100214&quot;&gt;
        ///  &lt;Mapping Computer=&quot;BuildServerA&quot;
        ///           OriginalQuality=&quot;*&quot;
        ///           NewQuality=&quot;Under Investigation&quot;
        ///           Script=&quot;PrepareForInvestigation.ps1&quot; /&gt;
        ///&lt;/DeploymentMappings&gt;.
        /// </summary>
        internal static string DeployerConfigurationWithBlankMappingNamespace {
            get {
                return ResourceManager.GetString("DeployerConfigurationWithBlankMappingNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;DeploymentMappings xmlns=&quot;http://www.readify.net/TfsDeployer/DeploymentMappings20100214&quot;&gt;
        ///  &lt;Mapping Computer=&quot;BuildServerA&quot;
        ///           OriginalQuality=&quot;*&quot;
        ///           NewQuality=&quot;Under Investigation&quot;
        ///           Script=&quot;PrepareForInvestigation.ps1&quot; /&gt;
        ///&lt;/DeploymentMappings&gt;.
        /// </summary>
        internal static string DeployerConfigurationWithoutBuildDefinitionPattern {
            get {
                return ResourceManager.GetString("DeployerConfigurationWithoutBuildDefinitionPattern", resourceCulture);
            }
        }
    }
}
