using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using TfsDeployer.Configuration;

namespace Tests.TfsDeployer.MappingEvaluatorTests
{
    /// <summary>
    /// Quickly builds a Mapping object and populates it with defaults that will match those
    /// generated by the BuildStatusChangeEventBuilder.
    /// </summary>
    internal class MappingBuilder
    {
        private readonly Mapping _mapping;

        public MappingBuilder()
        {
            var templateEvent = new BuildStatusChangeEventBuilder().BuildStatusChangeEvent;

            _mapping = new Mapping
            {
                Computer = Environment.MachineName,
                OriginalQuality = templateEvent.StatusChange.OldValue,
                NewQuality = templateEvent.StatusChange.NewValue,
                PermittedUsers = templateEvent.ChangedBy,
                Status = "Succeeded,PartiallySucceeded",
            };
        }

        public string Computer { set { _mapping.Computer = value; } }
        public string OriginalQuality { set { _mapping.OriginalQuality = value; } }
        public string NewQuality { set { _mapping.NewQuality = value; } }
        public string PermittedUsers { set { _mapping.PermittedUsers = value; } }
        public string Status { set { _mapping.Status = value; } }

        public Mapping Mapping { get { return _mapping; } }
    }
}
